// Built-in default theme (used as the fallback when a user theme is missing
// tokens, per DESIGN.md §6.5). This is the *frontend's* default — the
// `Dark.legit-theme.json` file on disk is the canonical "Dark" theme and
// loads through the same code path as user themes.

import type { ThemeDocument } from "../lib/types";

export const DEFAULT_THEME: ThemeDocument = {
  format: "legit-theme",
  formatVersion: 1,
  name: "Dark (built-in default)",
  description: "Used as the fallback when other themes have missing tokens.",
  palette: {
    "main-bg": "#1e1e1e",
    "main-fg": "#e0e0e0",
    "panel-bg": "#252526",
    "panel-border": "#333333",
    accent: "#4a9eff",
    "accent-hover": "#6ab4ff",
    "accent-fg": "#ffffff",
    danger: "#e58e26",
    "danger-hover": "#f4a340",
    success: "#3498db",
    warning: "#f1fa8c",
    "subtle-fg": "#888888",
    "input-bg": "#2d2d30",
    "console-bg": "#1a1a1a",
    "stderr-fg": "#e58e26",
  },
  tokens: {
    "app.bg": "main-bg",
    "app.fg": "main-fg",
    "panel.bg": "panel-bg",
    "panel.fg": "main-fg",
    "panel.border": "panel-border",
    "panel.header.bg": "panel-bg",
    "panel.header.fg": "main-fg",
    "tab.bg": "panel-bg",
    "tab.fg": "subtle-fg",
    "tab.active.bg": "accent",
    "tab.active.fg": "accent-fg",
    "tab.border": "panel-border",
    "panel-tab.bg": "panel-bg",
    "panel-tab.fg": "subtle-fg",
    "panel-tab.active.bg": "input-bg",
    "panel-tab.active.fg": "main-fg",
    "panel-tab.border": "panel-border",
    "button.bg": "panel-bg",
    "button.fg": "main-fg",
    "button.hover.bg": "input-bg",
    "button.primary.bg": "accent",
    "button.primary.hover.bg": "accent-hover",
    "button.primary.fg": "accent-fg",
    "button.danger.bg": "danger",
    "button.danger.hover.bg": "danger-hover",
    "button.danger.fg": "main-bg",
    "input.bg": "input-bg",
    "input.fg": "main-fg",
    "input.border": "panel-border",
    "input.focus.border": "accent",
    "console.bg": "console-bg",
    "console.fg": "main-fg",
    "console.stdout.fg": "main-fg",
    "console.stderr.fg": "stderr-fg",
    "console.prompt.fg": "accent",
    "divider.bg": "panel-border",
    "divider.hover.bg": "accent",
    "scrollbar.thumb": "panel-border",
    "scrollbar.thumb.hover": "subtle-fg",
    "scrollbar.track": "main-bg",
    "subtle.fg": "subtle-fg",
    "error.fg": "danger",
    "success.fg": "success",
    "warning.fg": "warning",
    "diff.added.bg": "success",
    "diff.added.fg": "main-fg",
    "diff.removed.bg": "danger",
    "diff.removed.fg": "main-fg",
    "branch.current.fg": "accent",
    "commit.signed.indicator": "success",
  },
};
